# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addDdlWin.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addDdlDialog(object):
    def setupUi(self, addDdlDialog):
        addDdlDialog.setObjectName("addDdlDialog")
        addDdlDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        addDdlDialog.resize(800, 84)
        addDdlDialog.setMinimumSize(QtCore.QSize(800, 84))
        addDdlDialog.setMaximumSize(QtCore.QSize(800, 84))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/图标/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addDdlDialog.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(addDdlDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(addDdlDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 9, 1, 1)
        self.label = QtWidgets.QLabel(addDdlDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(addDdlDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(addDdlDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(addDdlDialog)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.timeEdit2 = QtWidgets.QTimeEdit(addDdlDialog)
        self.timeEdit2.setObjectName("timeEdit2")
        self.gridLayout.addWidget(self.timeEdit2, 0, 10, 1, 1)
        self.timeEdit1 = QtWidgets.QTimeEdit(addDdlDialog)
        self.timeEdit1.setObjectName("timeEdit1")
        self.gridLayout.addWidget(self.timeEdit1, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.wholeDayCheckBox = QtWidgets.QCheckBox(addDdlDialog)
        self.wholeDayCheckBox.setChecked(True)
        self.wholeDayCheckBox.setObjectName("wholeDayCheckBox")
        self.gridLayout.addWidget(self.wholeDayCheckBox, 0, 11, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(addDdlDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 7, 1, 5)
        self.locationLineEdit = QtWidgets.QLineEdit(addDdlDialog)
        self.locationLineEdit.setObjectName("locationLineEdit")
        self.gridLayout.addWidget(self.locationLineEdit, 1, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(addDdlDialog)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(addDdlDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 1)
        self.importanceComboBox = QtWidgets.QComboBox(addDdlDialog)
        self.importanceComboBox.setObjectName("importanceComboBox")
        self.importanceComboBox.addItem("")
        self.importanceComboBox.addItem("")
        self.importanceComboBox.addItem("")
        self.gridLayout.addWidget(self.importanceComboBox, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(addDdlDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(addDdlDialog)
        self.buttonBox.accepted.connect(addDdlDialog.accept)
        self.buttonBox.rejected.connect(addDdlDialog.reject)
        self.wholeDayCheckBox.stateChanged['int'].connect(addDdlDialog.enable_time_set)
        QtCore.QMetaObject.connectSlotsByName(addDdlDialog)

    def retranslateUi(self, addDdlDialog):
        _translate = QtCore.QCoreApplication.translate
        addDdlDialog.setWindowTitle(_translate("addDdlDialog", "添加DDL"))
        self.label_4.setText(_translate("addDdlDialog", "到"))
        self.label.setText(_translate("addDdlDialog", "名称"))
        self.label_6.setText(_translate("addDdlDialog", "重要性"))
        self.label_2.setText(_translate("addDdlDialog", "日期"))
        self.wholeDayCheckBox.setText(_translate("addDdlDialog", "全天"))
        self.label_5.setText(_translate("addDdlDialog", "地点"))
        self.importanceComboBox.setItemText(0, _translate("addDdlDialog", "紧急"))
        self.importanceComboBox.setItemText(1, _translate("addDdlDialog", "重要"))
        self.importanceComboBox.setItemText(2, _translate("addDdlDialog", "普通"))
        self.label_3.setText(_translate("addDdlDialog", "时间"))
import source_rc
