# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setWin.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setWin(object):
    def setupUi(self, setWin):
        setWin.setObjectName("setWin")
        setWin.setWindowModality(QtCore.Qt.ApplicationModal)
        setWin.resize(430, 221)
        setWin.setMinimumSize(QtCore.QSize(430, 221))
        setWin.setMaximumSize(QtCore.QSize(430, 221))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/图标/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        setWin.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(setWin)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(setWin)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(setWin)
        self.tabWidget.setObjectName("tabWidget")
        self.normalTab = QtWidgets.QWidget()
        self.normalTab.setObjectName("normalTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.normalTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.normalTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.sortRuleComboBox = QtWidgets.QComboBox(self.normalTab)
        self.sortRuleComboBox.setObjectName("sortRuleComboBox")
        self.sortRuleComboBox.addItem("")
        self.sortRuleComboBox.addItem("")
        self.gridLayout_2.addWidget(self.sortRuleComboBox, 0, 1, 1, 6)
        self.label_4 = QtWidgets.QLabel(self.normalTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.normalTab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.warningWinPushButton = QtWidgets.QPushButton(self.normalTab)
        self.warningWinPushButton.setObjectName("warningWinPushButton")
        self.gridLayout_2.addWidget(self.warningWinPushButton, 3, 5, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.normalTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.normalTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.countDownDaySpinBox = QtWidgets.QSpinBox(self.normalTab)
        self.countDownDaySpinBox.setMaximum(365)
        self.countDownDaySpinBox.setObjectName("countDownDaySpinBox")
        self.gridLayout_2.addWidget(self.countDownDaySpinBox, 2, 1, 1, 1)
        self.countDownHourSpinBox = QtWidgets.QSpinBox(self.normalTab)
        self.countDownHourSpinBox.setMaximum(23)
        self.countDownHourSpinBox.setObjectName("countDownHourSpinBox")
        self.gridLayout_2.addWidget(self.countDownHourSpinBox, 2, 3, 1, 1)
        self.countDownMinuteSpinBox = QtWidgets.QSpinBox(self.normalTab)
        self.countDownMinuteSpinBox.setMaximum(59)
        self.countDownMinuteSpinBox.setObjectName("countDownMinuteSpinBox")
        self.gridLayout_2.addWidget(self.countDownMinuteSpinBox, 2, 5, 1, 1)
        self.warningWinCheckBox = QtWidgets.QCheckBox(self.normalTab)
        self.warningWinCheckBox.setObjectName("warningWinCheckBox")
        self.gridLayout_2.addWidget(self.warningWinCheckBox, 3, 1, 1, 2)
        self.warningToastCheckBox = QtWidgets.QCheckBox(self.normalTab)
        self.warningToastCheckBox.setObjectName("warningToastCheckBox")
        self.gridLayout_2.addWidget(self.warningToastCheckBox, 3, 3, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.normalTab, "")
        self.actionTab = QtWidgets.QWidget()
        self.actionTab.setObjectName("actionTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.actionTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.remTrayCheckBox = QtWidgets.QCheckBox(self.actionTab)
        self.remTrayCheckBox.setObjectName("remTrayCheckBox")
        self.gridLayout_4.addWidget(self.remTrayCheckBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.actionTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(setWin)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(setWin.accept)
        self.buttonBox.rejected.connect(setWin.reject)
        self.warningWinPushButton.clicked.connect(setWin.showWarnWinButtonPressAction)
        self.warningWinCheckBox.clicked.connect(setWin.setWarnSignalEmit)
        QtCore.QMetaObject.connectSlotsByName(setWin)

    def retranslateUi(self, setWin):
        _translate = QtCore.QCoreApplication.translate
        setWin.setWindowTitle(_translate("setWin", "设置"))
        self.label_2.setText(_translate("setWin", "倒计时小于"))
        self.sortRuleComboBox.setItemText(0, _translate("setWin", "重要性优先"))
        self.sortRuleComboBox.setItemText(1, _translate("setWin", "剩余时间优先"))
        self.label_4.setText(_translate("setWin", "小时"))
        self.label.setText(_translate("setWin", "排序规则"))
        self.warningWinPushButton.setText(_translate("setWin", "预警预览"))
        self.label_3.setText(_translate("setWin", "天"))
        self.label_5.setText(_translate("setWin", "分预警"))
        self.warningWinCheckBox.setText(_translate("setWin", "弹窗预警"))
        self.warningToastCheckBox.setText(_translate("setWin", "通知预警"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.normalTab), _translate("setWin", "常规"))
        self.remTrayCheckBox.setText(_translate("setWin", "记住关闭按钮动作"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actionTab), _translate("setWin", "动作"))
import source_rc
